import { Pet } from '../models/Pet';

const sampleData: Pet[] = [
    {
        id: '1',
        name: 'Goldie',
        category: 'dog',
        breed: 'Golden Retriever',
        age: 5,
        gender: 'male',
        imageURL: 'https://media.istockphoto.com/id/1971124912/photo/golden.webp?b=1&s=170667a&w=0&k=20&c=-y-rcJBHHpqWdVUpyHj61vh-QBIdf9r5YjpMsbIcto4=',
        description: 'Goldie is from New York City! She is super friendly and adores the beach.',
        createdAt: new Date('2019-05-01'),
    },
    {
        id: '2',
        name: 'Oreo',
        category: 'dog',
        breed: 'Border Collie',
        age: 2,
        gender: 'male',
        imageURL: 'https://www.rover.com/blog/wp-content/uploads/black-and-white-border-collie-e1711572989431.jpg',
        description: 'Oreo is from the Colorado! He loves nature and long walks.',
        createdAt: new Date('2022-04-23'),
    },
    {
        id: '3',
        name: 'Whiskers',
        category: 'cat',
        breed: 'Orange Tabby',
        age: 1,
        gender: 'female',
        imageURL: 'https://www.rover.com/blog/wp-content/uploads/cat-breathing-fast-orange-kitten.jpg',
        description: 'Whiskers is from a tiny town in Maine! She is very adventureous and loves to socialize.',
        createdAt: new Date('2023-02-12'),
    },
    {
        id: '4',
        name: 'Lia',
        category: 'cat',
        breed: 'Chartreux',
        age: 1,
        gender: 'female',
        imageURL: 'https://upload.wikimedia.org/wikipedia/commons/5/57/Chartreux-Bonheur-nuits_indiennes-neige2009.jpg',
        description: 'Lia is from Michigan! She loves quality time and enjoys naps.',
        createdAt: new Date('2023-06-3'),
    },
    {
        id: '5',
        name: 'Gio',
        category: 'hamster',
        breed: 'Syrian Hamster',
        age: 2,
        gender: 'male',
        imageURL: 'https://www.thesprucepets.com/thmb/U-V6GLIb6ZUmqvn4ysNnCAz6iT0=/2119x0/filters:no_upscale():strip_icc()/GettyImages-525140239-8808998be45e4bfa9140ae9dbcfe2d79.jpg',
        description: 'Gio is from Vermont! He loves to be active and loves quality time.',
        createdAt: new Date('2022-01-29'),
    },
    {
        id: '6',
        name: 'Mia',
        category: 'turtle',
        breed: 'Yellow-bellied Slider',
        age: 1,
        gender: 'female',
        imageURL: 'https://www.thesprucepets.com/thmb/06PRlw-hsQ5b3WDF4zw4nQulHaY=/1500x0/filters:no_upscale():strip_icc()/turtle-species-great-pets-4788330-hero-7883bb247ecb4d30910d08f717198d76.jpg',
        description: 'Mia is from New York! She is super sweet and very silly.',
        createdAt: new Date('2022-08-02'),
    },
];

export default sampleData;